behaviors:
  BBC:
    trainer_type: ppo
    keep_checkpoints: 100
    checkpoint_interval: 5000
    hyperparameters:
      batch_size: 10
      buffer_size: 1000
      learning_rate: 0.0003
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
    max_steps: 100000
    time_horizon: 64
    summary_freq: 10000
